#!/bin/bash

if [[ "$1" == "" ]]
	then
	echo "Usage: makejars <YYYYMMDD>"
	exit 1
fi

EXEJAR=pj2_${1}.jar
SRCJAR=pj2src_${1}.jar

cd ..
jar cf pj2/$SRCJAR pj2/.bashrc pj2/compile pj2/doc pj2/lib pj2/makejars pj2/packages.txt pj2/runjavadoc
cd pj2/lib
jar cf ../$EXEJAR `find . -name '*.class'` *.png
